### ISSUE TITLE
A small spelling mistake and a question about the test result.

### ISSUE THREAD

**Issue by mysteryboxed** [OoDBag/RISE#2]
Hi, thanks for your good work, i've found a small error in  _https://github.com/OoDBag/RISE#view-the-results)_

`python evaluate_results.py\
       --dataset "PACS" --output_foler "sweep1"`

'output_foler'  should be 'output_folder'

By the way, I have a question about the final result: In your paper, which result did you choose? The average corresponding test result or the average best test result? THANKS~

**Comment by OoDBag** [comment]
1. Thanks for pointing out the typo.  2. We use the training-domain validation metric to select the model to report results, so it should be averaged with corresponding test results, not the best test. (You can check the details in evaluate_results.py if needed)
